export const calendarStyles = {
  container: {
    width: '100%',
    padding: '24px',
    backgroundColor: 'white',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '24px',
  },
  title: {
    fontSize: '28px',
    fontWeight: 'bold',
    color: '#1a1a1a',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  navigation: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  navButton: {
    padding: '8px',
    backgroundColor: 'transparent',
    border: 'none',
    borderRadius: '50%',
    cursor: 'pointer',
    fontSize: '18px',
    color: '#1a1a1a', // Changed from #666 to darker
    transition: 'background-color 0.2s',
  },
  monthTitle: {
    fontSize: '20px',
    fontWeight: '600',
    color: '#1a1a1a', // Changed from #333 to darker
    minWidth: '180px',
    textAlign: 'center',
  },
  calendarGrid: {
    backgroundColor: 'white',
    border: '1px solid #e5e5e5',
    borderRadius: '8px',
    overflow: 'hidden',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
  },
  weekHeader: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
    backgroundColor: '#f8f9fa',
  },
  weekHeaderCell: {
    padding: '12px',
    fontSize: '14px',
    fontWeight: '600',
    color: '#1a1a1a', // Changed from #666 to darker
    textAlign: 'center',
    borderRight: '1px solid #e5e5e5',
  },
  daysGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
  },
  dayCell: {
    height: '96px',
    borderBottom: '1px solid #e5e5e5',
    borderRight: '1px solid #e5e5e5',
    padding: '8px',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
    position: 'relative',
  },
  dayCellHover: {
    backgroundColor: '#f0f8ff',
  },
  emptyCell: {
    backgroundColor: '#f8f9fa',
    cursor: 'default',
  },
  dayNumber: {
    fontSize: '14px',
    fontWeight: '500',
    marginBottom: '4px',
    color: '#1a1a1a', // Changed from #333 to darker
  },
  todayNumber: {
    color: '#2563eb',
    fontWeight: '700',
  },
  bookingBadge: {
    fontSize: '11px',
    backgroundColor: '#dbeafe',
    color: '#1e40af',
    padding: '2px 8px',
    borderRadius: '12px',
    display: 'inline-block',
    marginBottom: '2px',
  },
  bookingItem: {
    fontSize: '10px',
    color: '#1a1a1a', // Changed from #666 to darker
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    marginBottom: '1px',
  },
  moreBookings: {
    fontSize: '10px',
    color: '#374151', // Changed from #888 to darker
  },
  summaryGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '16px',
    marginTop: '24px',
  },
  summaryCard: {
    padding: '16px',
    borderRadius: '8px',
    color: 'white',
  },
  summaryCardBlue: {
    background: 'linear-gradient(135deg, #3b82f6, #2563eb)',
  },
  summaryCardGreen: {
    background: 'linear-gradient(135deg, #10b981, #059669)',
  },
  summaryCardPurple: {
    background: 'linear-gradient(135deg, #8b5cf6, #7c3aed)',
  },
  summaryCardOrange: {
    background: 'linear-gradient(135deg, #f59e0b, #d97706)',
  },
  summaryLabel: {
    fontSize: '14px',
    opacity: 0.95, // Increased from 0.9 for better visibility
    marginBottom: '4px',
  },
  summaryValue: {
    fontSize: '24px',
    fontWeight: 'bold',
  },
  backButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '12px 16px',
    color: '#2563eb',
    backgroundColor: 'transparent',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '14px',
    transition: 'background-color 0.2s',
  },
  createBookingButton: {
    marginLeft: 'auto',
    gap: '8px',
    padding: '12px 20px',
    backgroundColor: '#2563eb',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '600',
    transition: 'background-color 0.2s',
    display: 'flex',
    alignItems: 'center',
  },
  dayViewHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '24px',
  },
  dayViewTitle: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#1a1a1a',
  },
  scheduleGrid: {
    backgroundColor: 'white',
    border: '1px solid #e5e5e5',
    borderRadius: '8px',
    overflow: 'hidden',
    overflowX: 'auto',
  },
  scheduleHeader: {
    display: 'grid',
    gridTemplateColumns: '100px auto',
    borderBottom: '1px solid #e5e5e5',
    backgroundColor: '#f8f9fa',
  },
  scheduleHeaderLeft: {
    padding: '12px',
    fontWeight: '600',
    color: '#1a1a1a', // Changed from #666 to darker
    borderRight: '1px solid #e5e5e5',
    backgroundColor: '#f8f9fa',
    textAlign: 'center',
  },
  scheduleHeaderRight: {
    display: 'grid',
    gap: 0,
    backgroundColor: 'white',
  },
  staffHeader: {
    padding: '12px 8px',
    fontSize: '12px',
    fontWeight: '500',
    color: '#1a1a1a', // Changed from #666 to darker
    textAlign: 'center',
    borderRight: '1px solid #e5e5e5',
    backgroundColor: 'white',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '4px',
    minWidth: '120px',
  },
  timeRow: {
    display: 'grid',
    gridTemplateColumns: '100px auto',
    borderBottom: '1px solid #e5e5e5',
  },
  timeCell: {
    padding: '16px 12px',
    fontWeight: '500',
    color: '#1a1a1a', // Changed from #333 to darker
    backgroundColor: '#f8f9fa',
    borderRight: '1px solid #e5e5e5',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '12px',
    minHeight: '60px',
  },
  staffSlotsRow: {
    display: 'grid',
    gap: 0,
    backgroundColor: 'white',
  },
  staffSlot: {
    height: '60px',
    borderRight: '1px solid #e5e5e5',
    padding: '4px',
    backgroundColor: 'white',
    minWidth: '120px',
  },
  bookingBlock: {
    height: '100%',
    borderRadius: '4px',
    fontSize: '11px',
    padding: '6px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    gap: '2px',
  },
  bookingConfirmed: {
    backgroundColor: '#dcfce7',
    color: '#166534',
    border: '1px solid #bbf7d0',
  },
  bookingPending: {
    backgroundColor: '#fef3c7',
    color: '#92400e',
    border: '1px solid #fde68a',
  },
  bookingCancelled: {
    backgroundColor: '#fee2e2',
    color: '#991b1b',
    border: '1px solid #fecaca',
  },
  availableSlot: {
    height: '100%',
    borderRadius: '4px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
    color: '#9ca3af', // Slightly darker than #ccc but still subtle
    fontSize: '11px',
    backgroundColor: 'transparent',
  },
  // Modal styles
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  modal: {
    backgroundColor: 'white',
    borderRadius: '12px',
    padding: '24px',
    minWidth: '500px',
    maxHeight: '80vh',
    overflowY: 'auto',
    boxShadow: '0 10px 25px rgba(0,0,0,0.1)',
  },
  modalHeader: {
    fontSize: '20px',
    fontWeight: 'bold',
    marginBottom: '20px',
    color: '#1a1a1a',
  },
  formGroup: {
    marginBottom: '16px',
  },
  label: {
    display: 'block',
    fontSize: '14px',
    fontWeight: '500',
    color: '#1a1a1a', // Changed from #374151 to darker
    marginBottom: '6px',
  },
  input: {
    width: '100%',
    padding: '10px 12px',
    border: '1px solid #d1d5db',
    borderRadius: '6px',
    fontSize: '14px',
    backgroundColor: 'white',
    boxSizing: 'border-box',
    color: '#1a1a1a', // Added explicit text color
  },
  select: {
    width: '100%',
    padding: '10px 12px',
    border: '1px solid #d1d5db',
    borderRadius: '6px',
    fontSize: '14px',
    backgroundColor: 'white',
    boxSizing: 'border-box',
    color: '#1a1a1a', // Added explicit text color
  },
  formButtons: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '12px',
    marginTop: '24px',
  },
  cancelButton: {
    padding: '10px 20px',
    backgroundColor: 'transparent',
    border: '1px solid #d1d5db',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '14px',
    color: '#1a1a1a', // Changed from #374151 to darker
  },
  submitButton: {
    padding: '10px 20px',
    backgroundColor: '#2563eb',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '500',
  },
  disabledButton: {
    backgroundColor: '#9ca3af',
    cursor: 'not-allowed',
  },
}
