export const styles = {
  container: {
    height: 'calc(100vh - 80px)',
    width: 'calc(100vw - 26rem)', // Account for sidebar width
    maxWidth: 'none',
    backgroundColor: '#F3F4F6',
    display: 'flex',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    overflow: 'hidden',
    maxHeight: 'calc(100vh - 80px)',
    // Break out of both Container max-width AND Main padding
    marginLeft: 'calc(-50vw + 50% + 12rem)', // Adjust for sidebar (26rem / 2)
    marginRight: 'calc(-50vw + 50% - 12rem)',
    marginTop: '-4rem',
    marginBottom: '-6.4rem',
    padding: '0',
    position: 'relative',
    boxSizing: 'border-box',
  },
  leftPanel: {
    flex: '1 1 auto',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    maxHeight: 'calc(100vh - 60px)',
  },
  searchContainer: {
    backgroundColor: 'white',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
    padding: '16px',
    marginBottom: '16px',
  },
  searchInputWrapper: {
    position: 'relative',
    marginBottom: '16px',
  },
  searchIcon: {
    position: 'absolute',
    left: '12px',
    top: '12px',
    color: '#9CA3AF',
  },
  searchInput: {
    width: '100%',
    paddingLeft: '40px',
    paddingRight: '16px',
    paddingTop: '8px',
    paddingBottom: '8px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#D1D5DB',
    borderRadius: '8px',
    fontSize: '14px',
  },
  categoriesWrapper: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
    overflowX: 'auto',
  },
  categoryButton: {
    padding: '8px 16px',
    borderRadius: '8px',
    fontWeight: '500',
    whiteSpace: 'nowrap',
    backgroundColor: '#E5E7EB',
    color: '#374151',
    transition: 'all 0.2s',
  },
  categoryButtonActive: {
    backgroundColor: '#2563EB',
    color: 'white',
  },
  // Special styling for Combo category button
  categoryButtonCombo: {
    backgroundColor: '#FEF08A', // Yellow-200
    color: '#854D0E', // Yellow-900
    fontWeight: '600',
  },
  categoryButtonComboActive: {
    backgroundColor: '#FACC15', // Yellow-400
    color: '#713F12', // Yellow-950
    fontWeight: '600',
  },
  // Special styling for Popular category button
  categoryButtonPopular: {
    backgroundColor: '#FEF08A', // Yellow-200
    color: '#854D0E', // Yellow-900
    fontWeight: '600',
  },
  categoryButtonPopularActive: {
    backgroundColor: '#FACC15', // Yellow-400
    color: '#713F12', // Yellow-950
    fontWeight: '600',
  },
  productsContainer: {
    flex: '1 1 auto',
    backgroundColor: 'white',
    borderRadius: '8px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
    padding: '16px',
    overflowY: 'auto',
    minHeight: 0,
    maxHeight: '100%',
  },
  productsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '12px',
  },
  productCard: {
    backgroundColor: 'white',
    borderWidth: '2px',
    borderStyle: 'solid',
    borderColor: '#E5E7EB',
    borderRadius: '8px',
    padding: '16px',
    transition: 'all 0.2s',
    cursor: 'pointer',
    position: 'relative',
    textAlign: 'center',
  },
  productName: {
    fontWeight: '600',
    fontSize: '14px',
    marginBottom: '12px',
    color: '#1F2937',
  },
  priceContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '4px',
    marginBottom: '8px',
  },
  originalPrice: {
    fontSize: '12px',
    color: '#9CA3AF',
    textDecoration: 'line-through',
  },
  productPrice: {
    color: '#2563EB',
    fontWeight: 'bold',
    fontSize: '20px',
  },
  productDuration: {
    fontSize: '13px',
    color: '#6B7280',
  },
  discountBadge: {
    position: 'absolute',
    top: '8px',
    right: '8px',
    backgroundColor: '#EF4444',
    color: 'white',
    padding: '4px 8px',
    borderRadius: '4px',
    fontSize: '12px',
    fontWeight: 'bold',
  },
  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '300px',
  },
  emptyStateText: {
    marginTop: '16px',
    color: '#9CA3AF',
  },
  cartPanel: {
    width: 'min(350px, 30vw)',
    minWidth: '250px',
    backgroundColor: 'white',
    boxShadow: '0 10px 15px rgba(0,0,0,0.1)',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    maxHeight: 'calc(100vh - 60px)',
  },
  cartHeader: {
    padding: '12px',
    borderBottom: '1px solid #E5E7EB',
  },
  cartTitle: {
    fontSize: '18px',
    fontWeight: 'bold',
    display: 'flex',
    alignItems: 'center',
  },
  cartItems: {
    flex: '1 1 auto',
    overflowY: 'auto',
    padding: '12px',
    minHeight: 0,
    maxHeight: '100%',
  },
  emptyCart: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
  },
  emptyCartText: {
    marginTop: '16px',
    color: '#9CA3AF',
  },
  cartItemsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  cartItem: {
    backgroundColor: '#F9FAFB',
    borderRadius: '8px',
    padding: '12px',
  },
  cartItemHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '8px',
  },
  cartItemInfo: {
    flex: 1,
  },
  cartItemName: {
    fontWeight: '600',
    fontSize: '14px',
    marginBottom: '4px',
  },
  cartItemDetails: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  cartItemPrice: {
    color: '#2563EB',
    fontWeight: '500',
  },
  smallDiscountBadge: {
    backgroundColor: '#FEE2E2',
    color: '#991B1B',
    padding: '2px 6px',
    borderRadius: '4px',
    fontSize: '11px',
    fontWeight: 'bold',
  },
  cartItemDuration: {
    fontSize: '12px',
    color: '#6B7280',
    marginTop: '2px',
  },
  removeButton: {
    color: '#EF4444',
    cursor: 'pointer',
  },
  cartItemFooter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  quantityControls: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  quantityButton: {
    width: '32px',
    height: '32px',
    backgroundColor: '#E5E7EB',
    borderRadius: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  quantity: {
    width: '32px',
    textAlign: 'center',
    fontWeight: '600',
  },
  itemTotal: {
    fontWeight: 'bold',
  },
  totalsContainer: {
    borderTop: '1px solid #E5E7EB',
    padding: '16px',
  },
  grandTotal: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '20px',
    fontWeight: 'bold',
    borderTop: '1px solid #E5E7EB',
    paddingTop: '8px',
    marginTop: '8px',
  },
  checkoutButton: {
    width: '100%',
    backgroundColor: '#16A34A',
    color: 'white',
    padding: '12px',
    borderRadius: '8px',
    fontWeight: '600',
    marginTop: '16px',
    cursor: 'pointer',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    overflow: 'auto',
  },
  modal: {
    backgroundColor: 'white',
    borderRadius: '8px',
    maxWidth: '448px',
    width: '100%',
    maxHeight: '90vh',
    overflowY: 'auto',
    padding: '24px',
    boxSizing: 'border-box',
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '24px',
  },
  modalTitle: {
    fontSize: '24px',
    fontWeight: 'bold',
  },
  closeButton: {
    color: '#9CA3AF',
    cursor: 'pointer',
  },
  totalDisplay: {
    textAlign: 'center',
    padding: '16px',
    backgroundColor: '#F3F4F6',
    borderRadius: '8px',
    marginBottom: '24px',
  },
  totalLabel: {
    fontSize: '14px',
    color: '#6B7280',
  },
  totalAmount: {
    fontSize: '36px',
    fontWeight: 'bold',
    color: '#2563EB',
  },
  paymentMethodSection: {
    marginBottom: '24px',
  },
  label: {
    display: 'block',
    fontSize: '14px',
    fontWeight: '500',
    marginBottom: '12px',
  },
  paymentMethodGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
  },
  paymentMethodButton: {
    padding: '16px',
    borderWidth: '2px',
    borderStyle: 'solid',
    borderColor: '#E5E7EB',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  paymentMethodButtonActive: {
    borderWidth: '2px',
    borderStyle: 'solid',
    borderColor: '#2563EB',
    backgroundColor: '#EFF6FF',
  },
  paymentMethodLabel: {
    fontWeight: '600',
  },
  cashInputSection: {
    marginBottom: '24px',
  },
  cashInputWrapper: {
    position: 'relative',
  },
  dollarIcon: {
    position: 'absolute',
    left: '12px',
    top: '12px',
    color: '#9CA3AF',
  },
  cashInput: {
    width: '100%',
    paddingLeft: '40px',
    paddingRight: '16px',
    paddingTop: '8px',
    paddingBottom: '8px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#D1D5DB',
    borderRadius: '8px',
    fontSize: '14px',
  },
  changeDisplay: {
    marginTop: '12px',
    padding: '12px',
    backgroundColor: '#D1FAE5',
    borderRadius: '8px',
  },
  changeLabel: {
    fontSize: '14px',
    color: '#065F46',
  },
  changeAmount: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: '#059669',
  },
  message: {
    marginBottom: '16px',
    padding: '12px',
    borderRadius: '8px',
  },
  messageSuccess: {
    backgroundColor: '#D1FAE5',
    color: '#065F46',
  },
  messageError: {
    backgroundColor: '#FEE2E2',
    color: '#991B1B',
  },
  completeButton: {
    width: '100%',
    padding: '12px',
    borderRadius: '8px',
    fontWeight: '600',
    color: 'white',
    backgroundColor: '#2563EB',
    cursor: 'pointer',
  },
  completeButtonDisabled: {
    backgroundColor: '#9CA3AF',
    cursor: 'not-allowed',
  },
}
